---
- name: start mysql
  service: name=mysql state=started

- name: restart mysql
  service: name=mysql state=restarted

- name: stop mysql
  service: name=mysql state=stop

- name: start nginx
  service: name=nginx state=started

- name: restart nginx
  service: name=nginx state=restarted

- name: stop nginx
  service: name=nginx state=stop
