---
- name: Downloading Weblate
  git: repo=git://github.com/nijel/weblate.git dest=/var/www/weblate/ accept_hostkey=yes

- name: Copying service file
  copy: src=weblate.service dest=/etc/systemd/system/

- name: Copying settings file
  template: src=settings.py dest=/var/www/weblate/weblate/

- name: Preparing Weblate
  shell: /bin/python /var/www/weblate/manage.py migrate && /bin/python /var/www/weblate/manage.py collectstatic --noinput >> /var/log/weblate.log

- name: Copying uWSGI config file
  copy: src=weblate.ini dest=/var/www/weblate/

- name: Starting Weblate
  service: name=weblate state=started

- name: Configuring Nginx
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Starting Nginx
  service: name=nginx state=started

- name: Autostart services
  shell: chkconfig {{ item }} on
  with_items:
    - mysql
    - nginx
    - weblate

- wait_for: port=8080
