---
#- set_fact: launch="/bin/nohup /usr/bin/uwsgi /usr/local/weblate/weblate.ini >> /var/log/weblate.log &"

- name: Downloading Weblate
  git: repo=git://github.com/nijel/weblate.git dest=/usr/local/weblate/ accept_hostkey=yes

- name: Copying service file
  copy: src=weblate.service dest=/etc/systemd/system/

- name: Copying settings file
  template: src=settings.py dest=/usr/local/weblate/weblate/

- name: Preparing Weblate
  shell: /bin/python /usr/local/weblate/manage.py migrate && /bin/python /usr/local/weblate/manage.py collectstatic --noinput >> /var/log/weblate.log

- name: Copying uWSGI config file
  copy: src=weblate.ini dest=/usr/local/weblate/

- name: Starting Weblate
#  shell: '{{ launch }}'
  service: name=weblate state=started

- name: Configuring Nginx
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Starting Nginx
  service: name=nginx state=started

- name: Autostart services
  shell: chkconfig {{ item }} on
  with_items:
    - mysql
    - nginx
    - weblate

#- name: Autostart services
#  lineinfile: dest=/etc/rc.d/rc.local line='{{ launch }}'
