---
- name: Starting MySQL
  service: name=mysql state=started

- name: Changing root pass
  mysql_user: name=root password={{ rootpass }}
  ignore_errors: true

#- name: Creating MySQL user
#  mysql_user: login_user=root login_password='{{ rootpass }}' name=root host='localhost' password='{{ rootpass }}' priv=*.*:ALL state=present
#  shell: echo "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY '{{ rootpass }}' WITH GRANT OPTION;" | mysql -u root -p616603

- name: Creating MySQL user
#  mysql_user: login_user=root login_password={{ rootpass }} name=weblate host='%' password={{ weblatepass }} priv=weblate.*:ALL state=present
  shell: echo "GRANT ALL PRIVILEGES ON weblate.* TO 'weblate'@'%' IDENTIFIED BY '{{ weblatepass }}';" | mysql -u root -p{{ rootpass }}

- name: Creating MySQL user
#  mysql_user: login_user=root login_password={{ rootpass }} name=weblate host='localhost' password={{ weblatepass }} priv=weblate.*:ALL state=present
  shell: echo "GRANT ALL PRIVILEGES ON weblate.* TO 'weblate'@'%' IDENTIFIED BY '{{ weblatepass }}';" | mysql -u root -p{{ rootpass }}

- name: Creating new database
#  mysql_db: login_user=root login_password={{ rootpass }} name=weblate state=present
  shell: echo "CREATE DATABASE weblate;" | mysql -u root -p{{ rootpass }}

- name: Flushing privileges
  shell: echo "FLUSH PRIVILEGES;" | mysql -u root -p{{ rootpass }}
